"use strict";
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
console.log("Is car == 'toyota'? I predict False.");
console.log(car == 'toyota');
let age = 25;
console.log("Is age greater than 18? I predict True.");
console.log(age > 18);
console.log("Is age less than 21? I predict False.");
console.log(age < 21);
let temperature = 28;
console.log("Is temperature less than 0? I predict False.");
console.log(temperature < 0);
console.log("Is temperature greater than 20? I predict True.");
console.log(temperature > 20);
let isRaining = true;
console.log("Is it raining? I predict True.");
console.log(isRaining);
console.log("Is it sunny? I predict False.");
console.log(!isRaining);
let Assignment = true;
console.log("Will Sir check my Assignment? I predict True");
console.log(Assignment);
console.log("Sir will not check my Assignment? I predict False");
console.log(!Assignment);
let pakistanCapital = 'Islamabad';
console.log("Is 'Pakistan' Capital is Islamabad? I predict True.");
console.log(pakistanCapital == 'Islamabad');
console.log("Is 'Pakistan' Capital is Lahore? I predict False.");
console.log(pakistanCapital == 'Lahore');
